sudo: required
dist: trusty

services:
        - docker

language: go

go:
    - master

before_install:
    - sudo apt-get update
    - sudo apt-get install -y liblxc1 lxc-dev lxc
    - ./.deploy/install_consul.sh
    - ./.deploy/install_vault.sh
    - ./.deploy/install_nomad.sh

script:
    - nohup sudo consul agent -dev -bind=0.0.0.0 &
    - sleep 10
    - nohup sudo nomad  agent -dev -bind=0.0.0.0 &
    - sleep 10
    - nomad server-members
