sudo: required
dist: trusty

services:
        - docker

language: go

go:
    - master

before_install:
    - sudo apt-get update
    - sudo apt-get install -y liblxc1 lxc-dev lxc
    - ./.deploy/install_consul.sh
    - ./.deploy/install_vault.sh
    - ./.deploy/install_nomad.sh

script:
    - nohup consul agent -dev &
    - nohup nomad  agent -dev &
    - nomad server-members
